# Generated by Django 4.2.17 on 2025-01-20 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health_facility_app', '0002_alter_healthfacility_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_served', models.IntegerField()),
                ('avg_travel_time', models.FloatField(help_text='Average travel time in minutes')),
                ('distance_to_nearest_facility', models.FloatField(help_text='Distance to the nearest facility in kilometers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessibility_rating', models.CharField(choices=[('GOOD', 'Good'), ('MODERATE', 'Moderate'), ('POOR', 'Poor')], editable=False, max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('health_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_data', to='health_facility_app.healthfacility')),
            ],
        ),
    ]
