# Generated by Django 4.2.17 on 2025-01-20 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_facility_app', '0002_alter_healthfacility_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_of_allocation', models.DateTimeField(auto_now_add=True)),
                ('personnel_count', models.IntegerField()),
                ('duration_in_days', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('health_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='health_facility_app.healthfacility')),
            ],
        ),
    ]
