# Generated by Django 4.2.17 on 2025-01-20 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_allocation_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourceallocation',
            old_name='date_of_allocation',
            new_name='created_at',
        ),
    ]
