# Generated by Django 4.2.17 on 2025-02-04 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_allocation_app', '0002_rename_date_of_allocation_resourceallocation_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourceallocation',
            old_name='description',
            new_name='equipment',
        ),
        migrations.RenameField(
            model_name='resourceallocation',
            old_name='personnel_count',
            new_name='specialist',
        ),
    ]
