# Generated by Django 4.2.17 on 2025-01-18 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('total_population', models.IntegerField()),
                ('male_population', models.IntegerField()),
                ('female_population', models.IntegerField()),
                ('children_under_5', models.IntegerField()),
                ('youth_population', models.IntegerField()),
                ('adult_population', models.IntegerField()),
                ('elderly_population', models.IntegerField()),
                ('population_density', models.FloatField()),
                ('socioeconomic_status', models.CharField(choices=[('LOW', 'Low Income'), ('MIDDLE', 'Middle Income'), ('HIGH', 'High Income')], max_length=20)),
                ('unemployment_rate', models.FloatField()),
                ('literacy_rate', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('district', 'sector')},
            },
        ),
    ]
