# Generated by Django 4.2.17 on 2025-01-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_incident_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseaseincident',
            name='reporting_date',
        ),
        migrations.AlterField(
            model_name='diseaseincident',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('CONTAINED', 'Contained')], default='ACTIVE', max_length=20),
        ),
    ]
